port "49880"
bind_to_address "127.0.0.1"
music_directory "$HOME/music"
playlist_directory "$HOME/.config/mpd/playlists"
db_file "$HOME/.config/mpd/mpd.db"
log_file "$HOME/.config/mpd/mpd.log"
pid_file "$HOME/.config/mpd/mpd.pid"
state_file "$HOME/.config/mpd/mpdstate"
auto_update "yes"

audio_output {
		type "pulse"
		name "pulse audio"
}

audio_output {
		type                    "fifo"
		name                    "FIFO"
		path                    "/tmp/mpd.fifo"
		format                  "44100:16:2"
}
