#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

~/.config/polybar/launch.sh &
nitrogen --restore &
xrdb -load ~/.Xresources
picom &

bspc monitor -d 1 2 3 4 5

bspc config border_width         3
bspc config window_gap          35

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
